"""empty message

Revision ID: 02053f375c4e
Revises: 946b32b0d0cd
Create Date: 2020-10-11 06:08:57.944146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02053f375c4e'
down_revision = '946b32b0d0cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('artist_id', sa.Integer(), nullable=False))
    op.add_column('show', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('show', sa.Column('start_time', sa.String(length=25), nullable=True))
    op.add_column('show', sa.Column('vanue_id', sa.Integer(), nullable=False))
    op.drop_constraint('show_Artist_id_fkey', 'show', type_='foreignkey')
    op.drop_constraint('show_Vanue_id_fkey', 'show', type_='foreignkey')
    op.create_foreign_key(None, 'show', 'Artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'show', 'Venue', ['vanue_id'], ['id'])
    op.drop_column('show', 'Start_time')
    op.drop_column('show', 'Vanue_id')
    op.drop_column('show', 'Artist_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('Artist_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('show', sa.Column('Vanue_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('show', sa.Column('Start_time', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.drop_constraint(None, 'show', type_='foreignkey')
    op.create_foreign_key('show_Vanue_id_fkey', 'show', 'Venue', ['Vanue_id'], ['id'])
    op.create_foreign_key('show_Artist_id_fkey', 'show', 'Artist', ['Artist_id'], ['id'])
    op.drop_column('show', 'vanue_id')
    op.drop_column('show', 'start_time')
    op.drop_column('show', 'id')
    op.drop_column('show', 'artist_id')
    # ### end Alembic commands ###
